Repository tbhaxor/DonorGrid, pull requests merged in 2021-08, with the labels that each got.

#27 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: feature

#28 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: improvement

#29 Updated subtitle
  docs/index.html
Labels: improvement

#31 Implement django admin whitelabel using django-admin-interface
  DonorGrid/settings.py
  requirements.txt
Labels: feature

#32 Implement custom fields with donation
  Configuration/admin.py
  Configuration/migrations/0012_customfield.py
  Configuration/migrations/0013_customfield_help_text.py
  Configuration/migrations/0014_auto_20210812_2217.py
  Configuration/models.py
  Configuration/tests.py
  Configuration/urls.py
  Configuration/views.py
  Donation/migrations/0008_donation_custom_data.py
  Donation/models.py
  Donation/views.py
  Package/tests.py
Labels: feature

#34 Fixed whitelabel file issues and support production deployment
  .gitignore
  DonorGrid/settings.py
  DonorGrid/urls.py
  docker-compose.yaml
  uploads/.gitkeep
Labels: bug, improvement

#37 Implement SMTP and improve admin panel
  Callback/views.py
  Configuration/admin.py
  Configuration/migrations/0015_smtpsever.py
  Configuration/migrations/0016_auto_20210818_1907.py
  Configuration/migrations/0017_auto_20210818_1910.py
  Configuration/migrations/0018_smtpsever_event.py
  Configuration/migrations/0019_auto_20210818_1924.py
  Configuration/migrations/0020_auto_20210818_1926.py
  Configuration/migrations/0021_auto_20210818_1942.py
  Configuration/migrations/0022_auto_20210818_1958.py
  Configuration/migrations/0023_rename_smtpsever_smtpserver.py
  Configuration/models.py
  Configuration/tests.py
  Configuration/utils.py
  Donation/migrations/0009_alter_donation_options.py
  Donation/models.py
  Donation/views.py
  Donor/migrations/0004_alter_donor_options.py
  Donor/models.py
  DonorGrid/settings.py
  Package/migrations/0012_alter_package_options.py
  Package/models.py
  Package/tests.py
  README.md
  requirements.txt
Labels: feature

#38 Implement zapier and pabbly connect integration
  Callback/views.py
  Configuration/admin.py
  Configuration/migrations/0024_auto_20210821_0216.py
  Configuration/migrations/0025_automation.py
  Configuration/migrations/0026_alter_automation_name.py
  Configuration/migrations/0027_alter_automation_webhook_url.py
  Configuration/models.py
  Configuration/tests.py
  Configuration/utils.py
  Donation/views.py
Labels: improvement

#39 Check pabbly connect and zapier under integrations
  Donor/tests.py
  README.md
Labels: improvement

#41 Changed logo and copyright information
  docs/index.html
Labels: improvement

#42 Remove auto ssl and fix deployment
  .coveragerc
  .gitignore
  DEPLOYMENT.md
  docker-compose.yaml
  entrypoint.sh
  nginx.conf
  nginx.ssl.sh
  requirements.txt
Labels: improvement
